### ISSUE TITLE
READMEの先頭に一行加える

### ISSUE THREAD

**Issue by ringospoon** [ichikawapc/config-parse#13]
誰でも、手が空いたときにやって欲しいです。

README.md の先頭に次の一行を加えてほしいです。

```md
![CI Workflow](https://github.com/ichikawapc/config-parse/actions/workflows/scala.yml/badge.svg)
```

これによって、バックグラウンドで走っているsbtの成功/失敗がREADMEに出るようになります♪

**Comment by libe-igu** [comment]
違うブランチで作業しちゃった気がしたので、いったん巻き戻しました
